# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import paste_pb2 as paste__pb2


class PasteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPaste = channel.unary_unary(
                '/paste.PasteService/SendPaste',
                request_serializer=paste__pb2.PasteDTO.SerializeToString,
                response_deserializer=paste__pb2.EMPTY.FromString,
                )
        self.ReceivePaste = channel.unary_stream(
                '/paste.PasteService/ReceivePaste',
                request_serializer=paste__pb2.ByReceiver.SerializeToString,
                response_deserializer=paste__pb2.Paste.FromString,
                )


class PasteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceivePaste(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPaste': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPaste,
                    request_deserializer=paste__pb2.PasteDTO.FromString,
                    response_serializer=paste__pb2.EMPTY.SerializeToString,
            ),
            'ReceivePaste': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceivePaste,
                    request_deserializer=paste__pb2.ByReceiver.FromString,
                    response_serializer=paste__pb2.Paste.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paste.PasteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PasteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/paste.PasteService/SendPaste',
            paste__pb2.PasteDTO.SerializeToString,
            paste__pb2.EMPTY.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceivePaste(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/paste.PasteService/ReceivePaste',
            paste__pb2.ByReceiver.SerializeToString,
            paste__pb2.Paste.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
